export const STRATEGY_CHEAT_SHEET = [
    {
        id: "ai-matic-core",
        name: "AI-MATIC Core Entry",
        description: "AI-MATIC TF stack + POI analyzer (OB/FVG/Breaker/Liquidity) with priority sorting.",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 1,
        rules: [
            "TF stack: 1h context, 5m signal/management",
            "FVG: 3-svickova imbalance detekce (priority 1)",
            "OB: posledni opacna svicka pred impulsem (priority 2)",
            "Breaker: mitigace OB + close za extremem (priority 3)",
            "Liquidity pools: equal highs/lows, tolerance 0.2 %, min 3 dotyky",
            "Swing points window: 7 (pro highs/lows)",
            "POI sort: Breaker > OB > FVG > Liquidity",
        ],
    },
    {
        id: "ai-matic-x-smc",
        name: "AI-MATIC-X SMC Hierarchy",
        description: "Bull: HTF 12h/4h bias + LTF 1h/5m CHOCH/MSS; Bear: HTF 1d/4h bias + LTF 1h/15m entries.",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 2,
        rules: [
            "Bullish: HTF 12h/4h structure defines bias (HH/HL)",
            "Bearish: HTF 1d/4h structure defines bias (LH/LL)",
            "HTF key swings + POI zones: OB, FVG, Breaker, Liquidity pools",
            "LTF: 1h context + 5m (bull) / 15m (bear) displacement toward HTF bias",
            "LTF CHOCH confirms shift; MSS break + mitigation",
            "LTF OB/FVG aligns with HTF POI before entry",
            "Entry on pullback into HTF POI after inducement sweep",
            "Ignore LTF-only patterns without HTF context",
        ],
    },
    {
        id: "ai-matic-x-smart-money-combo",
        name: "AI-MATIC-X Smart Money Combo",
        description: "Smart Money combo: OB + liquidity, sweep/inducement, break/retest, FVG, volatility sizing, checklist gate.",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 2,
        rules: [
            "Order blocks + liquidity: identify OB volume zones; place SL outside OB to avoid stop hunts",
            "Liquidity sweep + inducement: detect fake breaks of key levels; enter after reversal confirmation",
            "Always combine sweep with EMA rules and candle patterns",
            "Break & retest: enter after confirmed retest; require volume reaction + LTF structure",
            "FVG: identify impulse gaps; use FVG as TP targets or SL placement",
            "Position sizing adapts to volatility; prefer entries after elevated volatility or stop-hunt move",
            "Checklist gate: require 7/10 confirmations",
            "1) EMA trend 8/21/50 without cross",
            "2) Candle pattern (modules 1-6)",
            "3) Increased volume",
            "4) BTC correlation / neutral stance",
            "5) Entry from OB zone",
            "6) Liquidity sweep confirmed",
            "7) Break & retest structure",
            "8) FVG present",
            "9) Near volume profile / S&R",
            "10) CoinGlass confirmation (OI, funding, volume)",
            "Valid entry only after combined checklist confirmation",
            "RODINA → POVOLENÉ CHOVÁNÍ (SCAN + OPEN)",
            "Provozní manuál pro scan i řízení otevřené pozice. Pokud to nesedí 1:1 → NO TRADE.",
            "RODINA 1 – TREND PULLBACK",
            "| Oblast | Pravidlo |",
            "| Kontext | 1h TREND + 5m TREND |",
            "| Směr | Pouze ve směru trendu |",
            "| Styl | Swing / držení |",
            "| Risk | 1R (RISK ON) |",
            "| Řízení | Trail za HL / LH |",
            "| Cíl | Pokračování trendu |",
            "| SMÍM | držet, trailovat, brát partial |",
            "| NESMÍM | chytat top/bottom, vstup v chaosu |",
            "⚠️ POZOR: Jakmile padne HL / LH → EXIT bez diskuze.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Struktura je důležitější než zisk.",
            "RODINA 2 – TREND CONTINUATION (BREAK + ACCEPTANCE)",
            "| Oblast | Pravidlo |",
            "| Kontext | Silný trend |",
            "| Směr | Ve směru trendu |",
            "| Styl | Momentum |",
            "| Risk | 1R (jen RISK ON) |",
            "| Řízení | Rychlé rozhodnutí |",
            "| Cíl | Expanze |",
            "| SMÍM | vstup po acceptance |",
            "| NESMÍM | vstup na první wick |",
            "⚠️ POZOR: Break, který se rychle vrátí, je neplatný.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Bez acceptance = žádný obchod.",
            "RODINA 3 – RANGE FADE (HIGH / LOW)",
            "| Oblast | Pravidlo |",
            "| Kontext | 1h + 5m RANGE |",
            "| Směr | Proti extrému |",
            "| Styl | Rychlý scalp |",
            "| Risk | 0.25–0.5R |",
            "| Řízení | Rychlý TP |",
            "| Cíl | Střed / opačná hrana |",
            "| SMÍM | brát zisk rychle |",
            "| NESMÍM | držet, doufat |",
            "⚠️ POZOR: Fade uprostřed range = chyba.",
            "⭐ NEJDŮLEŽITĚJŠÍ: V range se nevydělává držením.",
            "RODINA 4 – RANGE → TREND (BREAK & FLIP)",
            "| Oblast | Pravidlo |",
            "| Kontext | Dlouhá range |",
            "| Směr | Po potvrzení |",
            "| Styl | Přechod |",
            "| Risk | 1R |",
            "| Řízení | Pokud flip selže → EXIT |",
            "| Cíl | Začátek trendu |",
            "| SMÍM | vstup na retestu |",
            "| NESMÍM | předbíhat strukturu |",
            "⚠️ POZOR: Break bez retestu často selže.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Trend začíná až po flipu, ne při breaku.",
            "RODINA 6 – NO TRADE (CHOP)",
            "| Oblast | Pravidlo |",
            "| Kontext | Chaos / overlap |",
            "| Směr | ŽÁDNÝ |",
            "| Styl | Neobchodovat |",
            "| Risk | 0 |",
            "| Řízení | Zavřít platformu |",
            "| Cíl | Přežití |",
            "| SMÍM | jít pryč |",
            "| NESMÍM | zkoušet „něco vymyslet“ |",
            "⚠️ POZOR: Nuda = největší nepřítel.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Neobchodování je aktivní rozhodnutí.",
            "RYCHLÁ MAPA (NA PAMĚŤ)",
            "TREND + návrat → RODINA 1 → držím",
            "TREND + break → RODINA 2 → momentum",
            "RANGE → RODINA 3 → rychle ven",
            "RANGE + flip → RODINA 4 → začátek trendu",
            "Chaos → RODINA 6 → nic",
            "JAK TO POUŽÍVAT KAŽDÝ DEN",
            "1) Scan → určím rodinu",
            "2) Tabulka → podívám se, co smím",
            "3) Pokud to nesedí 1:1 → NO TRADE",
            "Když musíš přemýšlet, jak to „přizpůsobit“, už jsi mimo rodinu.",
        ],
    },
    {
        id: "ai-matic-scalp-scalpera",
        name: "AI-MATIC-SCALP Scalpera v2",
        description: "Scalpera Bot AI Matic Edition v2.0 for mid-frequency intraday scalps (10-15 trades/day).",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 3,
        rules: [
            "TrendScore fusion: EMA alignment * 0.4 + OI gradient * 0.3 + AI cone slope * 0.3",
            "Bias: TrendScore > 0.65 => LONG, < 0.35 => SHORT, else WAIT",
            "Volatility filter: ATR14/ATR50 < 0.5 => WAIT; > 1.5 => enter only on BOS",
            "Micro-confirmation: 3/4 must pass (EMA8>21>50, FVG/OB + vol>SMA20*1.2, AI cone > 0.6, funding aligned)",
            "Session windows: 08:00-12:00 UTC and 13:00-17:00 UTC, else session_filter=false",
            "Cone-FVG overlay: if 60% MC paths end inside FVG => return bias; >70% outside => breakout bias",
            "SentimentScore = funding*0.4 + oi_delta*0.4 + social*0.2 (LONG > 0.55, SHORT < 0.45)",
            "Auto-learning: log EMA/FVG/OI/funding context and adjust weights every ~100 trades",
        ],
    },
    {
        id: "ai-matic-decision-tree",
        name: "AI-MATIC Decision Tree – Market → Akce",
        description: "Rozhodovací strom A + Checklist B + Rodiny C + Risk protokol D pro Bybit Linear (1h/5m).",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 2,
        rules: [
            "A – KONKRÉTNÍ, OPERAČNÍ rozhodovací strom",
            "Bybit Linear Perpetuals",
            "primární TF: 5m",
            "kontext: 1h",
            "scan ~40 trhů",
            "binární výstupy",
            "žádné \"možná\"",
            "Ber to jako tvůj manuál pilota.",
            "ROZHODOVACÍ STROM – MARKET → AKCE",
            "(používej shora dolů, bez přeskakování)",
            "KROK 0 – KONTEXT (1h timeframe)",
            "Otázka 0.1: Je 1h trh v jasném trendu, nebo ne?",
            "PRAVIDLO (rychlé, vizuální):",
            "TREND 1h = posledních min. 2× HH/HL nebo LL/LH, svíčky nejsou překrývající",
            "NO TREND / RANGE 1h = overlap, wicky chaos, návraty do středu",
            "Výstup: 1h BULL TREND / 1h BEAR TREND / 1h RANGE / NEUTRAL",
            "Poznámka: Nikdy netraduješ proti 1h trendu swingově. Proti 1h směru jen scalp / range fade.",
            "KROK 1 – REŽIM TRHU (5m)",
            "Otázka 1.1: Je 5m TREND nebo RANGE?",
            "TREND (5m) – splněno 2 ze 3: struktura HH/HL nebo LL/LH; swingi jsou roztažené, málo overlapu; návraty jsou korekce, ne plné retrace",
            "RANGE (5m): overlap svíček; návraty ke středu; falešné breaky",
            "Výstup (binárně): TREND / RANGE",
            "KROK 2 – SMĚR (pouze pokud TREND)",
            "Otázka 2.1: Je trend BULL nebo BEAR?",
            "Pravidlo: BULL = HH + HL; BEAR = LL + LH",
            "Výstup: BULL TREND / BEAR TREND",
            "Pokud není jasné → není trend → RANGE",
            "KROK 3 – RISK STAV",
            "Otázka 3.1: Je dnes RISK ON nebo RISK OFF?",
            "RISK OFF, pokud platí alespoň JEDNO: 2 ztrátové obchody po sobě; −2R za den; extrémní chop / whipsaw; únava, zrychlené rozhodování; jsi blízko funding času a držel bys pozici proti logice",
            "Výstup: RISK ON / RISK OFF",
            "KROK 4 – KVALITA SETUPU",
            "Otázka 4.1: Je to HIGH PROB nebo LOW PROB?",
            "Použij bodování (0–5): jasný režim (trend/range); shoda s 1h kontextem; dobrý RR (min 1:2); čistá struktura; žádný konflikt (S/R, VWAP, range high/low)",
            "Výstup: HIGH PROB = ≥4 body; LOW PROB = ≤3 body",
            "KONEČNÉ ROZHODNUTÍ – AKCE",
            "SCÉNÁŘ 1: TREND + BULL + HIGH PROB + RISK ON → LONG (swing/pullback, trail za HL, partial na logickém levelu)",
            "SCÉNÁŘ 2: TREND + BEAR + HIGH PROB + RISK ON → SHORT (swing/pullback, trail za LH)",
            "SCÉNÁŘ 3: RANGE + HIGH PROB → RANGE FADE (buy low / sell high, TP u opačné hrany, žádné držení)",
            "SCÉNÁŘ 4: LOW PROB nebo RISK OFF → NO TRADE nebo max 0.25R, rychlý scalp",
            "ABSOLUTNÍ ZÁKAZY: žádné přidávání; long v BEAR trendu (5m) jen proto, že \"je nízko\"; držení range breaku bez potvrzení struktury; přidávání do ztráty; změna plánu v otevřeném obchodu",
            "JAK TO POUŽÍVAT V PRAXI (SCAN 40 TRHŮ): 1h BULL/BEAR/RANGE; 5m TREND/RANGE; Směr BULL/BEAR/-; Risk ON/OFF; Prob HIGH/LOW; Akce LONG/SHORT/RANGE/NO TRADE; NO TRADE → okamžitě další trh",
            "C – REDUKCE SETUPŮ: 40 → 6 RODIN",
            "Cíl: při scanu nepřemýšlíš „který setup“, ale jen „do které rodiny to patří“",
            "RODINA 1 – TREND PULLBACK (HL/LH)",
            "Použití: 1h TREND; 5m TREND; směr = shoda s 1h",
            "Struktura: impuls → korekce → pokračování; korekce nedělá nový LL/HH; návrat do oblasti value (ne high/low extrém)",
            "A-setup podmínky: jasné HH/HL (long) nebo LL/LH (short); korekce max ~50–60 % impulsu; vstup po potvrzení (close zpět ve směru trendu); RR min. 1:2; žádný range na vyšším TF",
            "Akce: vstup po potvrzení korekce; řízení = checklist B (trail za HL/LH)",
            "RODINA 2 – TREND CONTINUATION / BREAK + ACCEPTANCE",
            "Použití: 1h TREND; 5m TREND; trh expanduje",
            "Struktura: break struktury; akceptace nad/pod levelem (ne jen wick)",
            "A-setup podmínky: break + 1–2 svíčky drží úroveň; žádný okamžitý návrat do range; prostor na RR (není hned vyšší TF level)",
            "Akce: agresivnější, ale jen RISK ON; pokud návrat zpět → okamžitý EXIT",
            "RODINA 3 – RANGE FADE (HIGH/LOW)",
            "Použití: 1h RANGE/NEUTRAL; 5m RANGE",
            "Struktura: jasně definované high/low; návraty ke středu",
            "A-setup podmínky: vstup u hrany range, ne uprostřed; rejection (wick + close zpět); cíl = opačná hrana / střed",
            "Akce: rychlý trade; žádné držení; žádné přidávání",
            "RODINA 4 – RANGE → TREND (BREAK & FLIP)",
            "Použití: 1h RANGE; 5m RANGE → BREAK",
            "Struktura: break range; retest drží; vzniká HH/HL nebo LL/LH",
            "A-setup podmínky: retest úspěšný (ne návrat do range); struktura se potvrzuje; prostor k pokračování",
            "Akce: vstup na retestu; pokud návrat do range → EXIT",
            "RODINA 5 – REVERSAL (OMEZENĚ)",
            "Použití: jen na extrémech; jen po vyčerpání trendu",
            "Struktura: climax pohyb; selhání pokračování; první změna struktury",
            "A-setup podmínky (velmi přísné): jasná divergence + strukturální break; malý risk; rychlý cíl",
            "Akce: 0.25–0.5R max; nikdy nedržet „na naději“",
            "RODINA 6 – NO TRADE (CHOP/CHAOS)",
            "Znaky: overlap; falešné breaky; žádný follow-through",
            "Akce: NIC; další trh",
            "MAPA: STROM A → RODINY: TREND+BULL = 1,2; TREND+BEAR = 1,2; RANGE = 3; RANGE→BREAK = 4; LOW PROB = 6; RISK OFF = 3 (malý risk) nebo 6",
            "DOČASNĚ ZAKÁZÁNO: komplexní patterny; mikro-timeframe signály; „pocitové“ vstupy; improvizace",
            "JAK TO POUŽÍVAT PŘI SCANU: 1h TREND/RANGE; 5m TREND/RANGE; Rodina 1/2/3/4/5/6; A-setup ANO/NE; Akce LONG/SHORT/FADE/NO TRADE",
            "RODINY – definice: Rodina = skupina obchodních situací, které se chovají podobně, řídí se stejnými pravidly a mají stejný způsob vstupu/řízení/výstupu",
            "Rodiny nejsou patterny. Rodiny jsou konteksty chování trhu.",
            "Proces: Strom A → určí TREND/RANGE/směr/risk; Rodina → určí typ obchodu; A-setup → stojí za risk; Checklist B → držení/zavírání",
            "Analogie: Rodina = jízda po dálnici/ve městě/v horách; Pattern = konkrétní zatáčka",
            "Praktická věta: „Neobchoduju setup. Obchoduju rodinu. Setup je jen spoušť.“",
            "RODINA → POVOLENÉ CHOVÁNÍ (SCAN + OPEN)",
            "Provozní manuál pro scan i řízení otevřené pozice. Pokud to nesedí 1:1 → NO TRADE.",
            "RODINA 1 – TREND PULLBACK",
            "| Oblast | Pravidlo |",
            "| Kontext | 1h TREND + 5m TREND |",
            "| Směr | Pouze ve směru trendu |",
            "| Styl | Swing / držení |",
            "| Risk | 1R (RISK ON) |",
            "| Řízení | Trail za HL / LH |",
            "| Cíl | Pokračování trendu |",
            "| SMÍM | držet, trailovat, brát partial |",
            "| NESMÍM | chytat top/bottom, vstup v chaosu |",
            "⚠️ POZOR: Jakmile padne HL / LH → EXIT bez diskuze.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Struktura je důležitější než zisk.",
            "RODINA 2 – TREND CONTINUATION (BREAK + ACCEPTANCE)",
            "| Oblast | Pravidlo |",
            "| Kontext | Silný trend |",
            "| Směr | Ve směru trendu |",
            "| Styl | Momentum |",
            "| Risk | 1R (jen RISK ON) |",
            "| Řízení | Rychlé rozhodnutí |",
            "| Cíl | Expanze |",
            "| SMÍM | vstup po acceptance |",
            "| NESMÍM | vstup na první wick |",
            "⚠️ POZOR: Break, který se rychle vrátí, je neplatný.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Bez acceptance = žádný obchod.",
            "RODINA 3 – RANGE FADE (HIGH / LOW)",
            "| Oblast | Pravidlo |",
            "| Kontext | 1h + 5m RANGE |",
            "| Směr | Proti extrému |",
            "| Styl | Rychlý scalp |",
            "| Risk | 0.25–0.5R |",
            "| Řízení | Rychlý TP |",
            "| Cíl | Střed / opačná hrana |",
            "| SMÍM | brát zisk rychle |",
            "| NESMÍM | držet, doufat |",
            "⚠️ POZOR: Fade uprostřed range = chyba.",
            "⭐ NEJDŮLEŽITĚJŠÍ: V range se nevydělává držením.",
            "RODINA 4 – RANGE → TREND (BREAK & FLIP)",
            "| Oblast | Pravidlo |",
            "| Kontext | Dlouhá range |",
            "| Směr | Po potvrzení |",
            "| Styl | Přechod |",
            "| Risk | 1R |",
            "| Řízení | Pokud flip selže → EXIT |",
            "| Cíl | Začátek trendu |",
            "| SMÍM | vstup na retestu |",
            "| NESMÍM | předbíhat strukturu |",
            "⚠️ POZOR: Break bez retestu často selže.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Trend začíná až po flipu, ne při breaku.",
            "RODINA 6 – NO TRADE (CHOP)",
            "| Oblast | Pravidlo |",
            "| Kontext | Chaos / overlap |",
            "| Směr | ŽÁDNÝ |",
            "| Styl | Neobchodovat |",
            "| Risk | 0 |",
            "| Řízení | Zavřít platformu |",
            "| Cíl | Přežití |",
            "| SMÍM | jít pryč |",
            "| NESMÍM | zkoušet „něco vymyslet“ |",
            "⚠️ POZOR: Nuda = největší nepřítel.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Neobchodování je aktivní rozhodnutí.",
            "RYCHLÁ MAPA (NA PAMĚŤ)",
            "TREND + návrat → RODINA 1 → držím",
            "TREND + break → RODINA 2 → momentum",
            "RANGE → RODINA 3 → rychle ven",
            "RANGE + flip → RODINA 4 → začátek trendu",
            "Chaos → RODINA 6 → nic",
            "JAK TO POUŽÍVAT KAŽDÝ DEN",
            "1) Scan → určím rodinu",
            "2) Tabulka → podívám se, co smím",
            "3) Pokud to nesedí 1:1 → NO TRADE",
            "Když musíš přemýšlet, jak to „přizpůsobit“, už jsi mimo rodinu.",
            "CHEAT-SHEET ROZHODOVACÍHO STROMU (VIZUÁLNĚ)",
            "1️⃣ 1H KONTEXT – „KAM TO TEČE?“",
            "![Image](https://howtotrade.com/wp-content/uploads/2025/02/Bullish-Market-Structure-Higher-High-and-Higher-Low-1024x518.png)",
            "![Image](https://www.writofinance.com/wp-content/uploads/2025/04/Lower-lows-and-lower-highs-Schematics.webp)",
            "![Image](https://www.brookstradingcourse.com/wp-content/uploads/2023/04/EURUSD-Monthly-March-Bull-Bar-Overlapping-Candlesticks.png)",
            "CO HLEDÁŠ NA GRAFU",
            "TREND: jasná schodovitá struktura.",
            "TREND: HH + HL (bull) / LL + LH (bear).",
            "TREND: svíčky se nepřekrývají.",
            "RANGE / NEUTRAL: chaos.",
            "RANGE / NEUTRAL: overlap.",
            "RANGE / NEUTRAL: návraty tam a zpět.",
            "JAK TO POUŽÍT",
            "1h nerozhoduje vstup.",
            "1h zakazuje směry.",
            "⚠️ POZOR",
            "❌ kreslení mikrolinií",
            "❌ „ale na 5m je signál“",
            "❌ snaha chytat vrchol/dno",
            "1h = filtr, ne spoušť.",
            "2️⃣ 5M REŽIM – „DRŽET NEBO BRÁT RYCHLE?“",
            "![Image](https://tradethatswing.com/wp-content/uploads/2022/09/impulse-corrective.jpg)",
            "![Image](https://www.tradingsim.com/hs-fs/hubfs/Imported_Blog_Media/5m-Charts-Banner-1024x576-1.png?height=576&name=5m-Charts-Banner-1024x576-1.png&width=1024)",
            "TREND (5m): impuls → korekce → impuls.",
            "TREND (5m): korekce nebere celé impulsy zpět.",
            "TREND (5m): swingi mají prostor.",
            "RANGE (5m): overlap.",
            "RANGE (5m): falešné breaky.",
            "RANGE (5m): cena se vrací ke středu.",
            "JAK TO POUŽÍT",
            "TREND → držím, trailuju.",
            "RANGE → beru rychle nebo nic.",
            "⚠️ NEJČASTĚJŠÍ CHYBA",
            "❌ považovat první break za trend",
            "Když si nejsi jistý do 10 s → RANGE.",
            "3️⃣ SMĚR – „POUDY TLAČÍ VĚTŠÍ HRÁČI?“",
            "![Image](https://www.xs.com/storage/blogs/ca77a99c-d140-4667-b163-e3f5197a30f8/higher-highs-and-higher-lows-img.webp)",
            "![Image](https://www.writofinance.com/wp-content/uploads/2025/04/Lower-lows-and-lower-highs-Schematics.webp)",
            "BULL: vyšší high.",
            "BULL: vyšší low.",
            "BULL: pullbacky jsou slabé.",
            "BEAR: nižší low.",
            "BEAR: nižší high.",
            "BEAR: návraty nahoru jsou odmítány.",
            "JAK TO POUŽÍT",
            "Trend = jen jeden směr.",
            "Druhý směr neexistuje.",
            "⚠️ KRITICKÁ CHYBA",
            "❌ „je to nízko, tak long“",
            "Bez trendu není směr.",
            "4️⃣ RISK ON / RISK OFF – „SMÍM DNES TLAČIT?“",
            "![Image](https://cdn.autonomous.ai/production/ecm/250116/the-perfect-trading-desk-setup-for-crypto-traders%281%29.webp)",
            "![Image](https://tradersync.com/wp-content/uploads/2019/09/Trading-Stages-Emotion-tradersync.jpg)",
            "RISK ON: klid.",
            "RISK ON: jasná struktura.",
            "RISK ON: žádná série ztrát.",
            "RISK OFF: po SL.",
            "RISK OFF: chop.",
            "RISK OFF: mentální tlak.",
            "RISK OFF: únava.",
            "JAK TO POUŽÍT",
            "RISK ON = plný plán.",
            "RISK OFF = malý risk nebo nic.",
            "⚠️ NEJHORŠÍ PAST",
            "❌ „setup je dobrý, tak musím“",
            "Ty nejsi stroj → risk se mění.",
            "5️⃣ HIGH PROB vs LOW PROB – „OBCHOD, NEBO POKUŠENÍ?“",
            "![Image](https://s3.tradingview.com/p/pidtNPAi_mid.webp)",
            "![Image](https://tradeciety.com/hubfs/Support%20Resistance.gif)",
            "HIGH PROB: všechno sedí.",
            "HIGH PROB: žádný vnitřní konflikt.",
            "HIGH PROB: víš přesně, kde jsi špatně a kde bereš zisk.",
            "LOW PROB: musíš si to vysvětlovat.",
            "LOW PROB: málo místa.",
            "LOW PROB: „nějak to vyjde“.",
            "JAK TO POUŽÍT",
            "HIGH PROB → obchod.",
            "LOW PROB → ignoruj.",
            "⚠️ NEJVĚTŠÍ NEPŘÍTEL",
            "❌ nuda",
            "❌ potřeba být v trhu",
            "Neobchodování je pozice.",
            "VIZUÁLNÍ ZKRATKA (ZAPAMATUJ SI)",
            "TREND má schody.",
            "RANGE má chaos.",
            "HIGH PROB je ticho v hlavě.",
            "LOW PROB je vysvětlování.",
            "JAK S TÍM PRACOVAT (PRAKTICKY)",
            "Otevřeš graf.",
            "Neptáš se „kde vstoupit“.",
            "Ptáš se: je to trend nebo chaos?",
            "Ptáš se: smím držet?",
            "Ptáš se: smím riskovat?",
            "Teprve pak řešíš vstup.",
            "B) CHECKLIST – HOLD / EXIT (DETAILNÍ VÝKLAD)",
            "Ber to jako mentální radar, který běží při každé nové 5m svíčce.",
            "Základní pravidlo: Checklist není o maximalizaci zisku. Checklist je o ochraně struktury a kapitálu.",
            "1) INVALIDACE STRUKTURY → EXIT OKAMŽITĚ",
            "![Image](https://www.tradingwithrayner.com/wp-content/uploads/2021/09/6.-new-Low.png)",
            "![Image](https://optimusfutures.com/blog/wp-content/uploads/2016/12/general-trend.png)",
            "CO TO ZNAMENÁ: Obchod už nemá důvod existovat. To, na čem byl postaven (trend), přestalo platit.",
            "JAK TO POZNÁŠ NA GRAFU (5m) – LONG (trend pullback): vznikne nižší low (LL) pod posledním HL; 5m svíčka zavře pod HL.",
            "JAK TO POZNÁŠ NA GRAFU (5m) – SHORT: vznikne vyšší high (HH); close nad LH.",
            "Close je rozhodující, ne wick.",
            "⚠️ NA CO SI DÁT POZOR: ❌ „To byl jen stop hunt“ ❌ posouvání SL ❌ čekání na další svíčku.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Struktura > PnL. Správný exit se často cítí „předčasně“.",
            "2) ZMĚNA REŽIMU (TREND → RANGE) → PARTIAL / EXIT",
            "![Image](https://substackcdn.com/image/fetch/%24s_%21QuTt%21%2Cw_1200%2Ch_600%2Cc_fill%2Cf_jpg%2Cq_auto%3Agood%2Cfl_progressive%3Asteep%2Cg_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F21cf7c5d-01fe-4cfe-9e02-fa4b9b89748c_915x567.png)",
            "![Image](https://s3.tradingview.com/b/bwoxHF0s_mid.webp)",
            "CO TO ZNAMENÁ: Trend nezmizel, ale přestal fungovat. Trh ztrácí momentum.",
            "JAK TO VIDÍŠ: 3–4 svíčky overlap; žádné nové HH/LL; návraty ke středu pohybu. Trend přestává „dýchat“.",
            "CO DĚLÁŠ: pokud máš +1R nebo víc → PARTIAL; pokud máš málo / BE → EXIT.",
            "⚠️ POZOR: ❌ držení trendu v chopu ❌ „ještě to zkusí jednou“.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Raději odejdu z funkčního obchodu příliš brzy než pozdě z nefunkčního.",
            "3) LOGICKÝ LEVEL → PARTIAL",
            "![Image](https://s3.tradingview.com/r/RQnLfaNE_mid.webp?v=1589473117)",
            "![Image](https://26693533.fs1.hubspotusercontent-eu1.net/hubfs/26693533/Imported_Blog_Media/Big-Round-Number-Support-Resistance-1.png)",
            "CO TO ZNAMENÁ: Trh dorazil tam, kde ostatní budou brát zisk.",
            "JAK TO POZNÁŠ: předchozí swing high/low; high/low range; silný impuls = 1–2R hotovo.",
            "CO DĚLÁŠ: bereš 30–50 %; stop posouváš na BE nebo za strukturu.",
            "⚠️ POZOR: ❌ chtít „všechno“ ❌ žádný plán na partial.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Partial = kupuješ si klid.",
            "4) TREND JE STÁLE ZDRAVÝ → HOLD",
            "![Image](https://highstrike.com/wp-content/uploads/2025/06/Example-of-an-Uptrend-with-Multiple-Pullbacks.svg)",
            "![Image](https://www.tradingwithrayner.com/wp-content/uploads/2018/12/2-2.png)",
            "CO TO ZNAMENÁ: Nic se nezměnilo. Trh dělá přesně to, co má.",
            "JAK TO VIDÍŠ: korekce jsou mělké; žádné silné rejection proti tobě; nové HH/LL se tvoří.",
            "CO DĚLÁŠ: NIC. Jen posouváš trail podle pravidel.",
            "⚠️ POZOR: ❌ brát zisk jen proto, že „už je dost“ ❌ koukat na PnL místo struktury.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Nech vítězné obchody dýchat.",
            "5) ČASOVÉ PRAVIDLO → EXIT / PARTIAL",
            "![Image](https://img.phemex.com/v1/fcb73e57-18f0-4901-922d-3cc4af0cc2a0/1280-x1280.PNG)",
            "![Image](https://www.smbtraining.com/blog/wp-content/uploads/2013/03/time-stop-YUM.jpg)",
            "CO TO ZNAMENÁ: Trh nepostupuje, i když by měl.",
            "JAK TO URČÍŠ: trend trade = 6–10 svíček bez nového HH/LL; range trade = 3–5 svíček bez reakce.",
            "CO DĚLÁŠ: malý zisk / BE → EXIT; větší zisk → PARTIAL.",
            "⚠️ POZOR: ❌ „ještě chvíli“ ❌ čekání bez důvodu.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Když trh neplatí rychle, něco je špatně.",
            "6) RISK OFF TRIGGER → OCHRANNÁ AKCE",
            "![Image](https://tradersync.com/wp-content/uploads/2019/09/Trading-Stages-Emotion-tradersync.jpg)",
            "![Image](https://a.c-dn.net/c/content/dam/publicsites/igcom/uk/images/ContentImage/overtrading%402x%20%281%29.png/jcr%3Acontent/renditions/original-size.webp)",
            "CO TO ZNAMENÁ: I dobrý obchod může být špatný, když jsi ve špatném stavu.",
            "SIGNÁLY: jsi po SL; cítíš tlak; blíží se funding / konec dne.",
            "CO DĚLÁŠ: utahuješ trail nebo EXIT.",
            "⚠️ POZOR: ❌ „tenhle obchod mě zachrání“.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Kapitál chráníš dřív, než vyděláváš.",
            "RYCHLÁ PAMĚŤOVKA:",
            "Struktura padla? → EXIT",
            "Trend slábne? → PARTIAL",
            "Level dosažen? → PARTIAL",
            "Trend zdravý? → HOLD",
            "Čas bez pohybu? → EXIT",
            "Hlavu nemám? → EXIT",
            "FINÁLNÍ PRINCIP: Checklist není o tom, kolik vyděláš. Je o tom, kolik chyb denně neuděláš.",
            "Cvičení: 20 historických obchodů; u každé 5m svíčky otázka 1–6; po 50–100 opakováních se rozhodování zautomatizuje",
            "D – RISK ON / RISK OFF PROTOKOL",
            "RISK ON: max risk 1R; povoleny rodiny 1,2,3; povoleno držet trend; žádné porušení checklistu B",
            "RISK OFF: max risk 0.25R; povoleny rodina 3 nebo 6; žádné swing držení; žádné přidávání",
            "Automatický RISK OFF (stačí jedno): −2R za den; 2 ztrátové obchody po sobě; nutkání „si to vzít zpátky“; zrychlené klikání; přeskakování checklistu; chop/whipsaw; falešné breaky; nelze jasně určit TREND/RANGE do 10 s; funding konflikt",
            "Návrat na RISK ON: 1 čistý A-setup bez porušení pravidel; mentální klid; jasný režim trhu; ne dřív než další obchod",
            "Denní kill switch: −3R za den; 3 porušení pravidel; pocit „je mi to jedno“ → konec obchodování na den",
            "Limity: max 5 obchodů/den; max 2 otevřené pozice; max 1 obchod/trh",
            "Přepnutí režimu – rychlá karta: -2R/2x SL/chop/únava/funding konflikt → RISK OFF; čistý A-setup + klid → RISK ON",
            "Pořadí systému: Strom A → Rodina C → Risk protokol D → Checklist B (nikdy opačně)",
            "Rituál (2 min před seancí): „Dnes jsem RISK ON/OFF.“ „Max ztráta dnes je __ R.“ „Obchoduju jen rodiny __.“",
            "FINÁLNÍ PRINCIP: Tvým úkolem není vydělat dnes. Tvým úkolem je přežít, abys mohl obchodovat zítra.",
            "PROVOZNÍ DENNÍ RUTINA (Bybit Linear · 40 trhů · 5m exekuce)",
            "0) RANNÍ NASTAVENÍ (5 min): Dnes jsem RISK ON/OFF; Max ztráta dnes −2R (RISK OFF) / −3R (KILL SWITCH); Obchoduju jen rodiny 1–3; Neobchoduju nudu. Neobchoduju chaos. Pokud váháš u bodu 1 → automaticky RISK OFF.",
            "1) SCAN 40 TRHŮ (20–30 min): 1h TREND/RANGE; 5m TREND/RANGE; Rodina 1/2/3/4/6; A-setup ANO/NE; Rodina 6 → další trh; výsledek scanu = 5–10 kandidátů max",
            "2) PŘÍPRAVA OBCHODŮ (5–10 min): invalidace, R, první logický partial; pokud nevíš do 10 s → škrtáš",
            "3) EXEKUCE – BĚHEM SEANCE: Strom A OK? Rodina povolená? Risk režim dovoluje velikost? Pokud ANO → vstup; pokud NE → žádná kreativita",
            "4) ŘÍZENÍ POZICE: každá nová 5m svíčka = Checklist B (struktura zrušena → EXIT; režim se mění → PARTIAL/EXIT; logický level → PARTIAL; trend zdravý → HOLD; čas bez pohybu → EXIT; risk off trigger → EXIT)",
            "5) AUTOMATICKÉ STOPKY DNE: −2R / 2× SL / mentální tlak → RISK OFF; −3R / porušení pravidel → konec obchodování",
            "6) POST-MARKET JOURNAL: Trh; Rodina; A-setup ANO/NE; Risk režim; Výsledek (R); Dodržel jsem pravidla ANO/NE; 1 věta: co správně / co nezopakovat",
            "7) TÝDENNÍ MINI-REVIEW: které rodiny vydělávají; kde porušuješ pravidla; co zjednodušíš (ne přidáš); nikdy neladíš systém v den ztráty",
            "Jedna věta, která tě ochrání: „Můj edge není vstup.\"",
        ],
    },
];
export function getCheatSheetSetup(id) {
    return STRATEGY_CHEAT_SHEET.find((setup) => setup.id === id) ?? null;
}
export function getDefaultCheatSheetSetupId() {
    return STRATEGY_CHEAT_SHEET[0]?.id ?? null;
}
