export const STRATEGY_CHEAT_SHEET = [
    {
        id: "ai-matic-core",
        name: "AI-MATIC Core Entry",
        description: "AI-MATIC TF stack (HTF 1h/15m + LTF 5m/1m) + POI analyzer (OB/FVG/Breaker/Liquidity) with priority sorting.",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 1,
        rules: [
            "HTF 1h: Určuje směr trhu. Nikdy neobchoduj proti němu.",
            "HTF 15m: Sleduj mini OB, přesnější korekce/pullbacky.",
            "LTF 5m: Vstupní patterny, potvrzení objemů, Smart Money kontext.",
            "LTF 1m: Absolutní přesnost vstupu, exekuce, správa SL/TS.",
            "FVG: 3-svickova imbalance detekce (priority 1)",
            "OB: posledni opacna svicka pred impulsem (priority 2)",
            "Breaker: mitigace OB + close za extremem (priority 3)",
            "Liquidity pools: equal highs/lows, tolerance 0.2 %, min 3 dotyky",
            "Swing points window: 7 (pro highs/lows)",
            "POI sort: Breaker > OB > FVG > Liquidity",
        ],
    },
    {
        id: "ai-matic-x-smc",
        name: "AI-MATIC-X SMC Hierarchy",
        description: "Bull: HTF 12h/4h bias + LTF 1h/5m CHOCH/MSS; Bear: HTF 1d/4h bias + LTF 1h/15m entries.",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 2,
        rules: [
            "Bullish: HTF 12h/4h structure defines bias (HH/HL)",
            "Bearish: HTF 1d/4h structure defines bias (LH/LL)",
            "HTF key swings + POI zones: OB, FVG, Breaker, Liquidity pools",
            "LTF: 1h context + 5m (bull) / 15m (bear) displacement toward HTF bias",
            "LTF CHOCH confirms shift; MSS break + mitigation",
            "LTF OB/FVG aligns with HTF POI before entry",
            "Entry on pullback into HTF POI after inducement sweep",
            "Ignore LTF-only patterns without HTF context",
        ],
    },
    {
        id: "ai-matic-x-smart-money-combo",
        name: "AI-MATIC-X Smart Money Combo",
        description: "Smart Money combo: OB + liquidity, sweep/inducement, break/retest, FVG, volatility sizing, checklist gate.",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 2,
        rules: [
            "Order blocks + liquidity: identify OB volume zones; place SL outside OB to avoid stop hunts",
            "Liquidity sweep + inducement: detect fake breaks of key levels; enter after reversal confirmation",
            "Always combine sweep with EMA rules and candle patterns",
            "Break & retest: enter after confirmed retest; require volume reaction + LTF structure",
            "FVG: identify impulse gaps; use FVG as TP targets or SL placement",
            "Position sizing adapts to volatility; prefer entries after elevated volatility or stop-hunt move",
            "Checklist gate: require 7/10 confirmations",
            "1) EMA trend 8/21/50 without cross",
            "2) Candle pattern (modules 1-6)",
            "3) Increased volume",
            "4) BTC correlation / neutral stance",
            "5) Entry from OB zone",
            "6) Liquidity sweep confirmed",
            "7) Break & retest structure",
            "8) FVG present",
            "9) Near volume profile / S&R",
            "10) CoinGlass confirmation (OI, funding, volume)",
            "Valid entry only after combined checklist confirmation",
            "RODINA → POVOLENÉ CHOVÁNÍ (SCAN + OPEN)",
            "Provozní manuál pro scan i řízení otevřené pozice. Pokud to nesedí 1:1 → NO TRADE.",
            "RODINA 1 – TREND PULLBACK",
            "| Oblast | Pravidlo |",
            "| Kontext | 1h TREND + 5m TREND |",
            "| Směr | Pouze ve směru trendu |",
            "| Styl | Swing / držení |",
            "| Risk | 1R (RISK ON) |",
            "| Řízení | Trail za HL / LH |",
            "| Cíl | Pokračování trendu |",
            "| SMÍM | držet, trailovat, brát partial |",
            "| NESMÍM | chytat top/bottom, vstup v chaosu |",
            "⚠️ POZOR: Jakmile padne HL / LH → EXIT bez diskuze.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Struktura je důležitější než zisk.",
            "RODINA 2 – TREND CONTINUATION (BREAK + ACCEPTANCE)",
            "| Oblast | Pravidlo |",
            "| Kontext | Silný trend |",
            "| Směr | Ve směru trendu |",
            "| Styl | Momentum |",
            "| Risk | 1R (jen RISK ON) |",
            "| Řízení | Rychlé rozhodnutí |",
            "| Cíl | Expanze |",
            "| SMÍM | vstup po acceptance |",
            "| NESMÍM | vstup na první wick |",
            "⚠️ POZOR: Break, který se rychle vrátí, je neplatný.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Bez acceptance = žádný obchod.",
            "RODINA 3 – RANGE FADE (HIGH / LOW)",
            "| Oblast | Pravidlo |",
            "| Kontext | 1h + 5m RANGE |",
            "| Směr | Proti extrému |",
            "| Styl | Rychlý scalp |",
            "| Risk | 0.25–0.5R |",
            "| Řízení | Rychlý TP |",
            "| Cíl | Střed / opačná hrana |",
            "| SMÍM | brát zisk rychle |",
            "| NESMÍM | držet, doufat |",
            "⚠️ POZOR: Fade uprostřed range = chyba.",
            "⭐ NEJDŮLEŽITĚJŠÍ: V range se nevydělává držením.",
            "RODINA 4 – RANGE → TREND (BREAK & FLIP)",
            "| Oblast | Pravidlo |",
            "| Kontext | Dlouhá range |",
            "| Směr | Po potvrzení |",
            "| Styl | Přechod |",
            "| Risk | 1R |",
            "| Řízení | Pokud flip selže → EXIT |",
            "| Cíl | Začátek trendu |",
            "| SMÍM | vstup na retestu |",
            "| NESMÍM | předbíhat strukturu |",
            "⚠️ POZOR: Break bez retestu často selže.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Trend začíná až po flipu, ne při breaku.",
            "RODINA 6 – NO TRADE (CHOP)",
            "| Oblast | Pravidlo |",
            "| Kontext | Chaos / overlap |",
            "| Směr | ŽÁDNÝ |",
            "| Styl | Neobchodovat |",
            "| Risk | 0 |",
            "| Řízení | Zavřít platformu |",
            "| Cíl | Přežití |",
            "| SMÍM | jít pryč |",
            "| NESMÍM | zkoušet „něco vymyslet“ |",
            "⚠️ POZOR: Nuda = největší nepřítel.",
            "⭐ NEJDŮLEŽITĚJŠÍ: Neobchodování je aktivní rozhodnutí.",
            "RYCHLÁ MAPA (NA PAMĚŤ)",
            "TREND + návrat → RODINA 1 → držím",
            "TREND + break → RODINA 2 → momentum",
            "RANGE → RODINA 3 → rychle ven",
            "RANGE + flip → RODINA 4 → začátek trendu",
            "Chaos → RODINA 6 → nic",
            "JAK TO POUŽÍVAT KAŽDÝ DEN",
            "1) Scan → určím rodinu",
            "2) Tabulka → podívám se, co smím",
            "3) Pokud to nesedí 1:1 → NO TRADE",
            "Když musíš přemýšlet, jak to „přizpůsobit“, už jsi mimo rodinu.",
        ],
    },
    {
        id: "ai-matic-scalp-scalpera",
        name: "Kombinovaná strategie",
        description: "EMA cross + RSI divergence + volume spike, MACD/RSI filtry, ATR trailing a TP 1.5.",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 3,
        rules: [
            "Kombinovaná strategie",
            "Primární timeframe 15 m určuje směr trendu; vstupy na 1 m timeframe.",
            "Vstupní signál: krátká EMA překříží dlouhou EMA.",
            "Překřížení nad dlouhou EMA signalizuje býčí trend; pod ní medvědí.",
            "Přidává se RSI divergence: cena a RSI se pohybují opačně, což naznačuje změnu momentum.",
            "Volume spike (prudký nárůst objemu) potvrzuje průraz nebo obrat trendu.",
            "Výstupní logika: trailing stop podle ATR (2,5×) nebo pevný TP s RRR 1.5.",
            "ATR trailing stop nastavuje stop-loss podle volatility, což chrání pozici.",
            "Integrace tržních znalostí",
            "Chartové patterny poskytují kontext; hlava-ramena a dvojitý vrchol signalizují obrat.",
            "MACD potvrzuje trendový směr; používá se na 15 m timeframe jako filtr.",
            "RSI na 1 m timeframe načasuje vstupy a odhaluje přeprodané/překoupené stavy.",
            "Kombinace MACD a RSI zvyšuje přesnost a snižuje falešné signály.",
            "Kellyho kritérium určují velikost pozice podle win-rate a poměru výhra/prohra.",
            "Volume spike analyzuje prudké zvýšení objemu, potvrzuje průrazy a upozorňuje na obraty.",
        ],
    },
    {
        id: "ai-matic-decision-tree",
        name: "AI-MATIC-TREE Decision Tree",
        description: "Deterministická kombinovaná entry logika s dopady pro chybějící moduly (CombinedEntryStrategy).",
        entryType: "LIMIT_MAKER_FIRST",
        side: "both",
        priority: 2,
        rules: [
          "Implementované „Dopady“ = explicitní fallback pravidla.",
          "Závislosti: VP/PoC/LVN, order blocks, GAP, trap reakce, low-volume filtr (LOWVOL).",
          "Dopady při chybě:",
          "• LOWVOL chybí → scalping zakázán.",
          "• VP chybí → PoC/VP TP zakázáno, použít pouze strukturální cíle.",
          "• OB chybí → OB vstupy zakázány; povolen pouze BOS + return k HTF struktuře.",
          "• GAP chybí → intraday TP1 pouze na struktuře.",
          "• TRAP chybí → intraday Entry2 (trap/BOS) vypnut.",
          "Strategie rozhoduje deterministicky podle CombinedEntryStrategy.ts (Modul 11 – ENTRY STRATEGIE).",
          "Režimy: SWING (potvrzená HTF reakce), INTRADAY (OB návraty, BOS/trap), SCALP (LVN/OB rejekce + BOS return).",
          "SWING: pouze HTF reaction, entry HTF_REACTION_ONLY, SL UNDER_SWING, TP SWING_PERCENT_4_6.",
          "INTRADAY: OB_RETURN nebo BOS_RETURN; TP1 GAP/structure, TP2 VP/HTF S/R, slisky OB nebo swing.",
          "SCALP: rejekce LVN/OB nebo BOS return, TP1 PoC/VP/nearsr, trailing 0.5–0.7 % aktivace.",
          "Trailing je aktivní jen pro scalping (ACTIVATE_AFTER_0_5_TO_0_7_PCT); jinak NONE.",
          "Strategie řídí blocks (např. IMPACT:LOWVOL_MISSING=>SCALP_DISABLED) a vrací no-trade pokud dependency chybí.",
          "Všechny signály jsou deterministické: závislosti + MarketSignals definují entryMode, TF, SL/TP a trailing.",
          "Čekající limit entry (doporučení): SCALP 5–10 min, INTRADAY 15–30 min, SWING 60–180 min.",
          "Pokud limit nestihne fill v okně nebo se změní struktura/rrr, setup zrušit a čekat na nový.",
        ]
    },
];
export function getCheatSheetSetup(id) {
    return STRATEGY_CHEAT_SHEET.find((setup) => setup.id === id) ?? null;
}
export function getDefaultCheatSheetSetupId() {
    return STRATEGY_CHEAT_SHEET[0]?.id ?? null;
}
