export type CheatSheetEntryType = "LIMIT_MAKER_FIRST" | "LIMIT" | "CONDITIONAL";

export type StrategyCheatSheetSetup = {
  id: string;
  name: string;
  description: string;
  entryType: CheatSheetEntryType;
  side: "long" | "short" | "both";
  priority: number;
  rules: string[];
  triggerOffsetBps?: number;
};

export const STRATEGY_CHEAT_SHEET: StrategyCheatSheetSetup[] = [
  {
    id: "ai-matic-core",
    name: "AI-MATIC Core Entry",
    description:
      "AI-MATIC TF stack + POI analyzer (OB/FVG/Breaker/Liquidity) with priority sorting.",
    entryType: "LIMIT_MAKER_FIRST",
    side: "both",
    priority: 1,
    rules: [
      "TF stack: 1h context, 15m micro, 5m signal, 1m confirmation/management",
      "FVG: 3-svickova imbalance detekce (priority 1)",
      "OB: posledni opacna svicka pred impulsem (priority 2)",
      "Breaker: mitigace OB + close za extremem (priority 3)",
      "Liquidity pools: equal highs/lows, tolerance 0.2 %, min 3 dotyky",
      "Swing points window: 7 (pro highs/lows)",
      "POI sort: Breaker > OB > FVG > Liquidity",
    ],
  },
  {
    id: "ai-matic-x-smc",
    name: "AI-MATIC-X SMC Hierarchy",
    description:
      "HTF 4h/1h bias + POI with LTF 15m/1m CHOCH/MSS and displacement pullback entries.",
    entryType: "LIMIT_MAKER_FIRST",
    side: "both",
    priority: 2,
    rules: [
      "HTF 4h/1h structure defines bias (HH/HL vs LH/LL)",
      "HTF key swings + POI zones: OB, FVG, Breaker, Liquidity pools",
      "LTF 15m/1m displacement toward HTF bias",
      "LTF CHOCH confirms shift; MSS break + mitigation",
      "LTF OB/FVG aligns with HTF POI before entry",
      "Entry on pullback into HTF POI after inducement sweep",
      "Ignore LTF-only patterns without HTF context",
    ],
  },
  {
    id: "ai-matic-x-smart-money-combo",
    name: "AI-MATIC-X Smart Money Combo",
    description:
      "Smart Money combo: OB + liquidity, sweep/inducement, break/retest, FVG, volatility sizing, checklist gate.",
    entryType: "LIMIT_MAKER_FIRST",
    side: "both",
    priority: 2,
    rules: [
      "Order blocks + liquidity: identify OB volume zones; place SL outside OB to avoid stop hunts",
      "Liquidity sweep + inducement: detect fake breaks of key levels; enter after reversal confirmation",
      "Always combine sweep with EMA rules and candle patterns",
      "Break & retest: enter after confirmed retest; require volume reaction + LTF structure",
      "FVG: identify impulse gaps; use FVG as TP targets or SL placement",
      "Position sizing adapts to volatility; prefer entries after elevated volatility or stop-hunt move",
      "Checklist gate: require 7/10 confirmations",
      "1) EMA trend 8/21/50 without cross",
      "2) Candle pattern (modules 1-6)",
      "3) Increased volume",
      "4) BTC correlation / neutral stance",
      "5) Entry from OB zone",
      "6) Liquidity sweep confirmed",
      "7) Break & retest structure",
      "8) FVG present",
      "9) Near volume profile / S&R",
      "10) CoinGlass confirmation (OI, funding, volume)",
      "Valid entry only after combined checklist confirmation",
    ],
  },
  {
    id: "ai-matic-scalp-scalpera",
    name: "AI-MATIC-SCALP Scalpera v2",
    description:
      "Scalpera Bot AI Matic Edition v2.0 for mid-frequency intraday scalps (10-15 trades/day).",
    entryType: "LIMIT_MAKER_FIRST",
    side: "both",
    priority: 3,
    rules: [
      "TrendScore fusion: EMA alignment * 0.4 + OI gradient * 0.3 + AI cone slope * 0.3",
      "Bias: TrendScore > 0.65 => LONG, < 0.35 => SHORT, else WAIT",
      "Volatility filter: ATR14/ATR50 < 0.5 => WAIT; > 1.5 => enter only on BOS",
      "Micro-confirmation: 3/4 must pass (EMA8>21>50, FVG/OB + vol>SMA20*1.2, AI cone > 0.6, funding aligned)",
      "Session windows: 08:00-12:00 UTC and 13:00-17:00 UTC, else session_filter=false",
      "Cone-FVG overlay: if 60% MC paths end inside FVG => return bias; >70% outside => breakout bias",
      "SentimentScore = funding*0.4 + oi_delta*0.4 + social*0.2 (LONG > 0.55, SHORT < 0.45)",
      "Auto-learning: log EMA/FVG/OI/funding context and adjust weights every ~100 trades",
    ],
  },
  {
    id: "ai-matic-decision-tree",
    name: "AI-MATIC Decision Tree – Market → Akce",
    description:
      "Rozhodovací strom A + Checklist B + Rodiny C + Risk protokol D pro Bybit Linear (5m/1h).",
    entryType: "LIMIT_MAKER_FIRST",
    side: "both",
    priority: 2,
    rules: [
      "A – KONKRÉTNÍ, OPERAČNÍ rozhodovací strom",
      "Bybit Linear Perpetuals",
      "primární TF: 5m",
      "kontext: 1h",
      "scan ~40 trhů",
      "binární výstupy",
      "žádné \"možná\"",
      "Ber to jako tvůj manuál pilota.",
      "ROZHODOVACÍ STROM – MARKET → AKCE",
      "(používej shora dolů, bez přeskakování)",
      "KROK 0 – KONTEXT (1h timeframe)",
      "Otázka 0.1: Je 1h trh v jasném trendu, nebo ne?",
      "PRAVIDLO (rychlé, vizuální):",
      "TREND 1h = posledních min. 2× HH/HL nebo LL/LH, svíčky nejsou překrývající",
      "NO TREND / RANGE 1h = overlap, wicky chaos, návraty do středu",
      "Výstup: 1h BULL TREND / 1h BEAR TREND / 1h RANGE / NEUTRAL",
      "Poznámka: Nikdy netraduješ proti 1h trendu swingově. Proti 1h směru jen scalp / range fade.",
      "KROK 1 – REŽIM TRHU (5m)",
      "Otázka 1.1: Je 5m TREND nebo RANGE?",
      "TREND (5m) – splněno 2 ze 3: struktura HH/HL nebo LL/LH; swingi jsou roztažené, málo overlapu; návraty jsou korekce, ne plné retrace",
      "RANGE (5m): overlap svíček; návraty ke středu; falešné breaky",
      "Výstup (binárně): TREND / RANGE",
      "KROK 2 – SMĚR (pouze pokud TREND)",
      "Otázka 2.1: Je trend BULL nebo BEAR?",
      "Pravidlo: BULL = HH + HL; BEAR = LL + LH",
      "Výstup: BULL TREND / BEAR TREND",
      "Pokud není jasné → není trend → RANGE",
      "KROK 3 – RISK STAV",
      "Otázka 3.1: Je dnes RISK ON nebo RISK OFF?",
      "RISK OFF, pokud platí alespoň JEDNO: 2 ztrátové obchody po sobě; −2R za den; extrémní chop / whipsaw; únava, zrychlené rozhodování; jsi blízko funding času a držel bys pozici proti logice",
      "Výstup: RISK ON / RISK OFF",
      "KROK 4 – KVALITA SETUPU",
      "Otázka 4.1: Je to HIGH PROB nebo LOW PROB?",
      "Použij bodování (0–5): jasný režim (trend/range); shoda s 1h kontextem; dobrý RR (min 1:2); čistá struktura; žádný konflikt (S/R, VWAP, range high/low)",
      "Výstup: HIGH PROB = ≥4 body; LOW PROB = ≤3 body",
      "KONEČNÉ ROZHODNUTÍ – AKCE",
      "SCÉNÁŘ 1: TREND + BULL + HIGH PROB + RISK ON → LONG (swing/pullback, trail za HL, partial na logickém levelu)",
      "SCÉNÁŘ 2: TREND + BEAR + HIGH PROB + RISK ON → SHORT (swing/pullback, trail za LH)",
      "SCÉNÁŘ 3: RANGE + HIGH PROB → RANGE FADE (buy low / sell high, TP u opačné hrany, žádné držení)",
      "SCÉNÁŘ 4: LOW PROB nebo RISK OFF → NO TRADE nebo max 0.25R, rychlý scalp",
      "ABSOLUTNÍ ZÁKAZY: žádné přidávání; long v BEAR trendu (5m) jen proto, že \"je nízko\"; držení range breaku bez potvrzení struktury; přidávání do ztráty; změna plánu v otevřeném obchodu",
      "JAK TO POUŽÍVAT V PRAXI (SCAN 40 TRHŮ): 1h BULL/BEAR/RANGE; 5m TREND/RANGE; Směr BULL/BEAR/-; Risk ON/OFF; Prob HIGH/LOW; Akce LONG/SHORT/RANGE/NO TRADE; NO TRADE → okamžitě další trh",
      "C – REDUKCE SETUPŮ: 40 → 6 RODIN",
      "Cíl: při scanu nepřemýšlíš „který setup“, ale jen „do které rodiny to patří“",
      "RODINA 1 – TREND PULLBACK (HL/LH)",
      "Použití: 1h TREND; 5m TREND; směr = shoda s 1h",
      "Struktura: impuls → korekce → pokračování; korekce nedělá nový LL/HH; návrat do oblasti value (ne high/low extrém)",
      "A-setup podmínky: jasné HH/HL (long) nebo LL/LH (short); korekce max ~50–60 % impulsu; vstup po potvrzení (close zpět ve směru trendu); RR min. 1:2; žádný range na vyšším TF",
      "Akce: vstup po potvrzení korekce; řízení = checklist B (trail za HL/LH)",
      "RODINA 2 – TREND CONTINUATION / BREAK + ACCEPTANCE",
      "Použití: 1h TREND; 5m TREND; trh expanduje",
      "Struktura: break struktury; akceptace nad/pod levelem (ne jen wick)",
      "A-setup podmínky: break + 1–2 svíčky drží úroveň; žádný okamžitý návrat do range; prostor na RR (není hned vyšší TF level)",
      "Akce: agresivnější, ale jen RISK ON; pokud návrat zpět → okamžitý EXIT",
      "RODINA 3 – RANGE FADE (HIGH/LOW)",
      "Použití: 1h RANGE/NEUTRAL; 5m RANGE",
      "Struktura: jasně definované high/low; návraty ke středu",
      "A-setup podmínky: vstup u hrany range, ne uprostřed; rejection (wick + close zpět); cíl = opačná hrana / střed",
      "Akce: rychlý trade; žádné držení; žádné přidávání",
      "RODINA 4 – RANGE → TREND (BREAK & FLIP)",
      "Použití: 1h RANGE; 5m RANGE → BREAK",
      "Struktura: break range; retest drží; vzniká HH/HL nebo LL/LH",
      "A-setup podmínky: retest úspěšný (ne návrat do range); struktura se potvrzuje; prostor k pokračování",
      "Akce: vstup na retestu; pokud návrat do range → EXIT",
      "RODINA 5 – REVERSAL (OMEZENĚ)",
      "Použití: jen na extrémech; jen po vyčerpání trendu",
      "Struktura: climax pohyb; selhání pokračování; první změna struktury",
      "A-setup podmínky (velmi přísné): jasná divergence + strukturální break; malý risk; rychlý cíl",
      "Akce: 0.25–0.5R max; nikdy nedržet „na naději“",
      "RODINA 6 – NO TRADE (CHOP/CHAOS)",
      "Znaky: overlap; falešné breaky; žádný follow-through",
      "Akce: NIC; další trh",
      "MAPA: STROM A → RODINY: TREND+BULL = 1,2; TREND+BEAR = 1,2; RANGE = 3; RANGE→BREAK = 4; LOW PROB = 6; RISK OFF = 3 (malý risk) nebo 6",
      "DOČASNĚ ZAKÁZÁNO: komplexní patterny; mikro-timeframe signály; „pocitové“ vstupy; improvizace",
      "JAK TO POUŽÍVAT PŘI SCANU: 1h TREND/RANGE; 5m TREND/RANGE; Rodina 1/2/3/4/5/6; A-setup ANO/NE; Akce LONG/SHORT/FADE/NO TRADE",
      "RODINY – definice: Rodina = skupina obchodních situací, které se chovají podobně, řídí se stejnými pravidly a mají stejný způsob vstupu/řízení/výstupu",
      "Rodiny nejsou patterny. Rodiny jsou konteksty chování trhu.",
      "Proces: Strom A → určí TREND/RANGE/směr/risk; Rodina → určí typ obchodu; A-setup → stojí za risk; Checklist B → držení/zavírání",
      "Analogie: Rodina = jízda po dálnici/ve městě/v horách; Pattern = konkrétní zatáčka",
      "Praktická věta: „Neobchoduju setup. Obchoduju rodinu. Setup je jen spoušť.“",
      "B – CHECKLIST PRO ŘÍZENÍ OTEVŘENÉ POZICE (5m, Bybit Linear)",
      "CHECKLIST: MÁM DRŽET NEBO ZAVŘÍT? (shora dolů – první ANO = akce)",
      "1) INVALIDACE STRUKTURY → EXIT OKAMŽITĚ",
      "PRO TREND LONG: vzniklo LL (nižší low než poslední HL); close 5m svíčky pod HL; silný impuls proti trendu (range-expansion)",
      "PRO TREND SHORT: vzniklo HH; close 5m svíčky nad LH",
      "ANO → EXIT (bez výjimky); NE → pokračuj",
      "2) ZMĚNA REŽIMU (TREND → RANGE) → PARTIAL / EXIT",
      "Signály: 3–4 svíčky overlap; žádná nová HH/LL; návrat ceny ke středu swingu",
      "ANO → pokud +1R nebo víc → PARTIAL (50–70 %); pokud < +1R → EXIT; NE → pokračuj",
      "3) DOSAŽEN LOGICKÝ TARGET → PARTIAL",
      "Levely: předchozí swing high/low; high/low range (5m nebo 1h); impulsní leg = 1R–2R",
      "ANO → vezmi 30–50 %; stop posuň na BE nebo za strukturu; NE → pokračuj",
      "4) TREND POKRAČUJE → HOLD",
      "Znaky: pullbacky jsou mělké; žádné silné rejection proti pozici; objem nevrcholí proti tobě",
      "ANO → HOLD; NE → pokračuj",
      "5) ČASOVÉ PRAVIDLO → EXIT / PARTIAL",
      "Trend trade: 6–10 svíček bez HH/LL; Range trade: 3–5 svíček",
      "ANO → malý zisk → EXIT; BE → EXIT; zisk >1R → PARTIAL; NE → pokračuj",
      "6) RISK OFF TRIGGER → OCHRANNÁ AKCE",
      "Spouštěče: denní limit blízko; mentální tlak; funding time blízko a nedává smysl držet",
      "ANO → stáhni risk (trail těsně) nebo EXIT i dobrý obchod; NE → pokračuj",
      "7) NIC Z VÝŠE UVEDENÉHO? → HOLD",
      "Pokud váháš → EXIT (váhání = ztráta struktury v hlavě)",
      "Rychlá verze: 1) Struktura zrušena → EXIT; 2) Režim se mění → PARTIAL/EXIT; 3) Level dosažen → PARTIAL; 4) Trend zdravý → HOLD; 5) Čas bez pohybu → EXIT; 6) Risk OFF → EXIT/TIGHT TRAIL; jinak HOLD",
      "DŮLEŽITÉ PRINCIPY: EXIT je úspěch podle procesu; PARTIAL = klid v hlavě; držet můžeš jen obchod se strukturou; nikdy „počkáme ještě jednu svíčku“",
      "Cvičení: 20 historických obchodů; u každé 5m svíčky otázka 1–7; po 50–100 opakováních se rozhodování zautomatizuje",
      "D – RISK ON / RISK OFF PROTOKOL",
      "RISK ON: max risk 1R; povoleny rodiny 1,2,3; povoleno držet trend; žádné porušení checklistu B",
      "RISK OFF: max risk 0.25R; povoleny rodina 3 nebo 6; žádné swing držení; žádné přidávání",
      "Automatický RISK OFF (stačí jedno): −2R za den; 2 ztrátové obchody po sobě; nutkání „si to vzít zpátky“; zrychlené klikání; přeskakování checklistu; chop/whipsaw; falešné breaky; nelze jasně určit TREND/RANGE do 10 s; funding konflikt",
      "Návrat na RISK ON: 1 čistý A-setup bez porušení pravidel; mentální klid; jasný režim trhu; ne dřív než další obchod",
      "Denní kill switch: −3R za den; 3 porušení pravidel; pocit „je mi to jedno“ → konec obchodování na den",
      "Limity: max 5 obchodů/den; max 2 otevřené pozice; max 1 obchod/trh",
      "Přepnutí režimu – rychlá karta: -2R/2x SL/chop/únava/funding konflikt → RISK OFF; čistý A-setup + klid → RISK ON",
      "Pořadí systému: Strom A → Rodina C → Risk protokol D → Checklist B (nikdy opačně)",
      "Rituál (2 min před seancí): „Dnes jsem RISK ON/OFF.“ „Max ztráta dnes je __ R.“ „Obchoduju jen rodiny __.“",
      "FINÁLNÍ PRINCIP: Tvým úkolem není vydělat dnes. Tvým úkolem je přežít, abys mohl obchodovat zítra.",
      "PROVOZNÍ DENNÍ RUTINA (Bybit Linear · 40 trhů · 5m exekuce)",
      "0) RANNÍ NASTAVENÍ (5 min): Dnes jsem RISK ON/OFF; Max ztráta dnes −2R (RISK OFF) / −3R (KILL SWITCH); Obchoduju jen rodiny 1–3; Neobchoduju nudu. Neobchoduju chaos. Pokud váháš u bodu 1 → automaticky RISK OFF.",
      "1) SCAN 40 TRHŮ (20–30 min): 1h TREND/RANGE; 5m TREND/RANGE; Rodina 1/2/3/4/6; A-setup ANO/NE; Rodina 6 → další trh; výsledek scanu = 5–10 kandidátů max",
      "2) PŘÍPRAVA OBCHODŮ (5–10 min): invalidace, R, první logický partial; pokud nevíš do 10 s → škrtáš",
      "3) EXEKUCE – BĚHEM SEANCE: Strom A OK? Rodina povolená? Risk režim dovoluje velikost? Pokud ANO → vstup; pokud NE → žádná kreativita",
      "4) ŘÍZENÍ POZICE: každá nová 5m svíčka = Checklist B (struktura zrušena → EXIT; režim se mění → PARTIAL/EXIT; logický level → PARTIAL; trend zdravý → HOLD; čas bez pohybu → EXIT; risk off trigger → EXIT)",
      "5) AUTOMATICKÉ STOPKY DNE: −2R / 2× SL / mentální tlak → RISK OFF; −3R / porušení pravidel → konec obchodování",
      "6) POST-MARKET JOURNAL: Trh; Rodina; A-setup ANO/NE; Risk režim; Výsledek (R); Dodržel jsem pravidla ANO/NE; 1 věta: co správně / co nezopakovat",
      "7) TÝDENNÍ MINI-REVIEW: které rodiny vydělávají; kde porušuješ pravidla; co zjednodušíš (ne přidáš); nikdy neladíš systém v den ztráty",
      "Jedna věta, která tě ochrání: „Můj edge není vstup.\"",
    ],
  },
];

export function getCheatSheetSetup(id: string): StrategyCheatSheetSetup | null {
  return STRATEGY_CHEAT_SHEET.find((setup) => setup.id === id) ?? null;
}

export function getDefaultCheatSheetSetupId(): string | null {
  return STRATEGY_CHEAT_SHEET[0]?.id ?? null;
}
