import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
const SettingsPanel = ({ settings, onUpdateSettings, onClose, }) => {
    const [local, setLocal] = useState(settings);
    const update = (field, value) => {
        const updated = { ...local, [field]: value };
        setLocal(updated);
        onUpdateSettings(updated);
    };
    return (_jsx("div", { className: "fixed inset-0 bg-background/80 backdrop-blur-xs flex items-center justify-center z-50", children: _jsxs("div", { className: "w-full max-w-lg bg-card text-card-foreground rounded-xl border shadow-lg p-6", children: [_jsxs("div", { className: "flex flex-col space-y-1.5 mb-6", children: [_jsx("h2", { className: "text-lg font-semibold leading-none tracking-tight", children: "Settings" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Configure your AI trading parameters." })] }), _jsxs("div", { className: "grid gap-4 py-4", children: [_jsxs("div", { className: "grid gap-2", children: [_jsx("label", { className: "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70", children: "Strategy Profile" }), _jsx("div", { className: "flex gap-2 flex-wrap", children: [
                                        { key: "off", label: "Off" },
                                        { key: "auto", label: "Auto" },
                                        { key: "scalp", label: "Scalp" },
                                        { key: "intraday", label: "Intraday" },
                                        { key: "swing", label: "Swing" },
                                        { key: "trend", label: "Trend" },
                                    ].map((opt) => (_jsx("button", { onClick: () => update("strategyProfile", opt.key), className: `inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input hover:bg-accent hover:text-accent-foreground h-9 px-3 ${local.strategyProfile === opt.key
                                            ? "bg-primary text-primary-foreground hover:bg-primary/90 border-primary"
                                            : "bg-background"}`, children: opt.label }, opt.key))) })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx("label", { className: "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70", children: "Entry Strictness" }), _jsx("div", { className: "flex gap-2 flex-wrap", children: [
                                        { key: "base", label: "Base" },
                                        { key: "relaxed", label: "Relaxed" },
                                        { key: "ultra", label: "Ultra" },
                                        { key: "test", label: "Test" },
                                    ].map((opt) => (_jsx("button", { onClick: () => update("entryStrictness", opt.key), className: `inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input hover:bg-accent hover:text-accent-foreground h-9 px-3 ${local.entryStrictness === opt.key
                                            ? "bg-blue-600 text-white hover:bg-blue-700 border-blue-600"
                                            : "bg-background"}`, children: opt.label }, opt.key))) })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx("label", { className: "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70", children: "Enforce Trading Hours" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: () => update("enforceSessionHours", true), className: `inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 border h-9 px-3 ${local.enforceSessionHours
                                                ? "bg-amber-500 text-black hover:bg-amber-600 border-amber-500"
                                                : "bg-background text-slate-300 border-input hover:bg-accent hover:text-accent-foreground"}`, children: "On" }), _jsx("button", { onClick: () => update("enforceSessionHours", false), className: `inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 border h-9 px-3 ${!local.enforceSessionHours
                                                ? "bg-emerald-600 text-white hover:bg-emerald-700 border-emerald-600"
                                                : "bg-background text-slate-300 border-input hover:bg-accent hover:text-accent-foreground"}`, children: "Off" })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { className: "grid gap-2", children: [_jsx("label", { className: "text-sm font-medium leading-none", children: "Base Risk %" }), _jsx("input", { type: "number", step: "0.01", value: local.baseRiskPerTrade, onChange: (e) => update("baseRiskPerTrade", Number(e.target.value)), className: "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx("label", { className: "text-sm font-medium leading-none", children: "Max Drawdown %" }), _jsx("input", { type: "number", step: "0.01", value: local.maxDrawdownPercent, onChange: (e) => update("maxDrawdownPercent", Number(e.target.value)), className: "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" })] })] }), _jsxs("div", { className: "grid gap-2", children: [_jsx("label", { className: "text-sm font-medium leading-none", children: "Custom Strategy" }), _jsx("textarea", { value: local.customStrategy, onChange: (e) => update("customStrategy", e.target.value), className: "flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50" })] })] }), _jsx("div", { className: "flex justify-end mt-6", children: _jsx("button", { onClick: onClose, className: "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 w-full sm:w-auto", children: "Close" }) })] }) }));
};
export default SettingsPanel;
